import { Metadata } from "next";
import { ReduxProvider } from "../redux/provider";
import NavbarAsk from "@/components/Navbar/NavbarAsk";

export const metadata: Metadata = {
    title: "Алтын уя - вопросы и ответы",
    description: "Generated by create next app",
};  

export default function Layout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en">
        <link rel='canonical' href='https://www.qurban.kg/ask-and-question/' />
        <body>
          <ReduxProvider>
            <NavbarAsk/>
            {children}
          </ReduxProvider>
        </body>
      </html>
    );
  }
  